export type GalleryItem={id:number;title:string;caption:string;category:string;year:string;src:string;alt:string;ratio:string};
export const galleryItems:GalleryItem[]=[
 {id:1,title:'Langkah Pertama Alcantara',caption:'Hari pertama pendidikan—wajah-wajah baru, satu tekad pengabdian.',category:'Education',year:'2022',src:'/images/memory/memory-1.svg',alt:'Ilustrasi dokumentasi hari pertama pendidikan Alcantara',ratio:'tall'},
 {id:2,title:'Tradisi Penerimaan',caption:'Momen letting resmi menjadi bagian keluarga besar PaPK.',category:'Letting',year:'2022',src:'/images/memory/memory-2.svg',alt:'Ilustrasi tradisi penerimaan letting',ratio:'wide'},
 {id:3,title:'Malam Prasetya',caption:'Sebuah janji yang menandai dimulainya pengabdian.',category:'Ceremony',year:'2022',src:'/images/memory/memory-3.svg',alt:'Ilustrasi malam upacara prasetya',ratio:'standard'},
 {id:4,title:'Kembali ke Hanggar',caption:'Pertemuan hangat setelah penugasan membawa kami ke penjuru negeri.',category:'Reunion',year:'2025',src:'/images/memory/memory-4.svg',alt:'Ilustrasi reuni alumni di hanggar',ratio:'tall'},
 {id:5,title:'Berbagi untuk Negeri',caption:'Bakti kesehatan dan edukasi untuk masyarakat pesisir.',category:'Professional Activities',year:'2026',src:'/images/memory/memory-5.svg',alt:'Ilustrasi kegiatan bakti kesehatan',ratio:'wide'},
 {id:6,title:'Di Antara Dua Penugasan',caption:'Potret sederhana yang menyimpan cerita persaudaraan panjang.',category:'Memories',year:'2024',src:'/images/memory/memory-6.svg',alt:'Ilustrasi kenangan alumni di sela penugasan',ratio:'standard'},
 {id:7,title:'Pelajaran di Cakrawala',caption:'Latihan lapangan membentuk ketelitian, ketangguhan, dan rasa percaya.',category:'Education',year:'2022',src:'/images/memory/memory-7.svg',alt:'Ilustrasi latihan lapangan',ratio:'wide'},
 {id:8,title:'Satu Meja, Banyak Cerita',caption:'Reuni kecil, tawa yang sama, dan rencana kolaborasi baru.',category:'Reunion',year:'2026',src:'/images/memory/memory-8.svg',alt:'Ilustrasi pertemuan reuni alumni',ratio:'standard'}
];
export type Article={slug:string;type:string;title:string;excerpt:string;date:string;author:string;readTime:string;cover:string;featured?:boolean;content:{heading?:string;body:string}[]};
export const articles:Article[]=[
 {slug:'menjaga-langit-merawat-sesama',type:'Alumni Story',title:'Menjaga langit, merawat sesama',excerpt:'Perjalanan seorang dokter penerbangan menemukan makna pengabdian di antara misi dan masyarakat.',date:'18 Agustus 2026',author:'Redaksi PaPK Alumni',readTime:'6 menit',cover:'/images/memory/memory-5.svg',featured:true,content:[{body:'Pengabdian tidak selalu hadir dalam suara mesin yang menggelegar. Kadang ia tumbuh dalam percakapan tenang, pemeriksaan sederhana, dan keyakinan bahwa setiap orang berhak mendapat perhatian terbaik.'},{heading:'Misi yang mendekatkan',body:'Kolaborasi lintas korps membawa tim alumni ke masyarakat pesisir. Keahlian yang berbeda bertemu pada tujuan yang sama: hadir, mendengar, lalu bekerja dengan sungguh-sungguh.'},{heading:'Jejak yang diteruskan',body:'Bagi keluarga besar PaPK, kegiatan ini bukan akhir sebuah agenda. Ia menjadi pengingat bahwa jejaring alumni hidup ketika pengetahuan dibagikan dan kepedulian diterjemahkan menjadi tindakan.'}]},
 {slug:'inovasi-pemeliharaan-untuk-kesiapan-operasi',type:'Achievement',title:'Inovasi pemeliharaan untuk kesiapan operasi',excerpt:'Gagasan sederhana alumni 29A memperkuat akurasi pencatatan teknis di satuan.',date:'2 Juli 2026',author:'Dian Prameswari',readTime:'4 menit',cover:'/images/memory/memory-7.svg',content:[{body:'Ketelitian adalah fondasi kesiapan. Sebuah tim kecil mengubah alur pencatatan menjadi lebih ringkas tanpa mengurangi kendali dan akuntabilitas.'},{heading:'Dari masalah sehari-hari',body:'Inovasi bermula dari keberanian mengamati pekerjaan rutin. Prototipe diuji bersama pengguna, diperbaiki, dan kini membantu pengambilan keputusan yang lebih cepat.'}]},
 {slug:'temu-lintas-penugasan-alcantara',type:'Reunion',title:'Temu lintas penugasan Alcantara',excerpt:'Jarak ribuan kilometer tidak menghentikan percakapan dan persaudaraan satu letting.',date:'21 Juni 2026',author:'Sekretariat Alcantara',readTime:'3 menit',cover:'/images/memory/memory-4.svg',content:[{body:'Dari berbagai wilayah pengabdian, layar-layar kecil menyala pada malam yang sama. Pertemuan itu mengembalikan keakraban sekaligus membuka ruang kolaborasi baru.'}]},
 {slug:'estafet-kepemimpinan-alumni',type:'Professional Story',title:'Estafet kepemimpinan di ruang profesional',excerpt:'Tiga alumni berbagi cara memimpin tim lintas generasi dengan empati dan ketegasan.',date:'12 Mei 2026',author:'Raka Mahendra',readTime:'7 menit',cover:'/images/memory/memory-3.svg',content:[{body:'Kepemimpinan bukan semata posisi. Ia adalah kesediaan menciptakan ruang aman untuk belajar, memberi arah yang jelas, dan bertanggung jawab atas keputusan bersama.'}]},
 {slug:'agenda-reuni-akbar-2026',type:'Announcement',title:'Agenda reuni akbar PaPK 2026',excerpt:'Catat tanggalnya dan siapkan kembali cerita terbaik dari setiap letting.',date:'4 April 2026',author:'Panitia Reuni',readTime:'2 menit',cover:'/images/memory/memory-8.svg',content:[{body:'Reuni akbar akan mempertemukan alumni lintas letting dalam rangkaian dialog profesi, malam kenangan, dan kegiatan sosial.'}]},
 {slug:'kabar-letting-penugasan-baru',type:'Letting Update',title:'Kabar letting: cakrawala penugasan baru',excerpt:'Menyapa rekan-rekan yang memulai babak pengabdian di wilayah baru.',date:'19 Maret 2026',author:'Desk Letting',readTime:'3 menit',cover:'/images/memory/memory-2.svg',content:[{body:'Perpindahan tugas membawa tantangan sekaligus kesempatan belajar. Jejaring alumni hadir agar setiap langkah baru tetap terasa dekat dengan rumah.'}]}
];
export const history=[
 {year:'1993',track:'PaPK',title:'Awal lintasan PaPK',text:'Pendidikan perwira karier membangun tradisi pengabdian lintas disiplin.'},
 {year:'2022',track:'Letting',title:'PaPK 29A dimulai',text:'Calon perwira dari beragam profesi bertemu dalam satu perjalanan pendidikan.'},
 {year:'2022',track:'ALCANTARA',title:'Nama Alcantara lahir',text:'Identitas letting menjadi simbol keluasan cakrawala dan keteguhan arah.'},
 {year:'2023',track:'Letting',title:'Penugasan pertama',text:'Alumni menyebar ke satuan dan wilayah pengabdian di seluruh Indonesia.'},
 {year:'2026',track:'PaPK',title:'Jejaring digital',text:'Memori, keahlian, dan peluang kolaborasi terhubung dalam satu rumah digital.'}
];
