export type Alumni={id:number;slug:string;fullName:string;academicTitle:string;militaryRank:string;letting:string;batch:string;year:string;corps:string;profession:string;specialization:string;region:string;unit:string;profileImage:string;shortBio:string;education:string[];achievements:string[];socialLinks:{linkedin?:string;instagram?:string};verified:boolean;featured:boolean;updatedAt:string;name:string;rank:string;role:string;city:string;initials:string;specialty:string};
type AlumniSeed=Omit<Alumni,'name'|'rank'|'role'|'city'|'initials'|'specialty'>;
const seeds:AlumniSeed[]=[
 {id:1,slug:'muhammad-sobri-maulana',fullName:'Muhammad Sobri Maulana',academicTitle:'S.T.',militaryRank:'Lettu Lek',letting:'ALCANTARA',batch:'PaPK 29A',year:'2022A',corps:'Elektronika',profession:'Perwira TNI AU',specialization:'Sistem Informasi',region:'Jakarta',unit:'Satuan TNI AU',profileImage:'https://i.pravatar.cc/300?img=12',shortBio:'Profesional teknologi yang berfokus pada transformasi digital dan kolaborasi alumni.',education:['S.T. Teknik Informatika','PaPK TNI AU 2022'],achievements:['Inisiator kolaborasi digital alumni'],socialLinks:{linkedin:'#'},verified:true,featured:true,updatedAt:'2026-08-28'},
 {id:2,slug:'aditya-pratama',fullName:'Aditya Pratama',academicTitle:'S.Tr.Han.',militaryRank:'Kapten Pnb',letting:'ALCANTARA',batch:'PaPK 29A',year:'2022A',corps:'Penerbang',profession:'Penerbang',specialization:'Operasi Penerbangan',region:'Jakarta',unit:'Koopsud I',profileImage:'https://i.pravatar.cc/300?img=11',shortBio:'Penerbang yang aktif mengembangkan budaya keselamatan dan profesionalisme.',education:['S.Tr.Han.'],achievements:['Flight safety award'],socialLinks:{},verified:true,featured:true,updatedAt:'2026-08-20'},
 {id:3,slug:'nadia-larasati',fullName:'Nadia Larasati',academicTitle:'dr.',militaryRank:'Lettu Kes',letting:'ALCANTARA',batch:'PaPK 29A',year:'2022A',corps:'Kesehatan',profession:'Dokter',specialization:'Kedokteran Penerbangan',region:'Jakarta',unit:'RSAU dr. Esnawan',profileImage:'https://i.pravatar.cc/300?img=47',shortBio:'Dokter dengan perhatian pada kesehatan penerbangan dan pengabdian masyarakat.',education:['Dokter Umum'],achievements:['Koordinator bakti kesehatan'],socialLinks:{instagram:'#'},verified:true,featured:true,updatedAt:'2026-07-14'},
 {id:4,slug:'raka-mahendra',fullName:'Raka Mahendra',academicTitle:'S.T.',militaryRank:'Kapten Lek',letting:'BIMANTARA',batch:'PaPK 28',year:'2021',corps:'Elektronika',profession:'Engineer',specialization:'Avionik',region:'Jawa Barat',unit:'Koharmatau',profileImage:'https://i.pravatar.cc/300?img=15',shortBio:'Engineer avionik dan mentor talenta teknologi.',education:['S.T. Elektro'],achievements:['Inovasi sistem pemeliharaan'],socialLinks:{linkedin:'#'},verified:true,featured:false,updatedAt:'2026-06-30'},
 {id:5,slug:'shafira-anindya',fullName:'Shafira Anindya',academicTitle:'S.A.P.',militaryRank:'Lettu Adm',letting:'ALCANTARA',batch:'PaPK 29A',year:'2022A',corps:'Administrasi',profession:'Administrator',specialization:'Tata Kelola',region:'Jakarta',unit:'Mabesau',profileImage:'https://i.pravatar.cc/300?img=45',shortBio:'Praktisi tata kelola organisasi dan pelayanan publik.',education:['S.A.P. Administrasi Publik'],achievements:['Program simplifikasi administrasi'],socialLinks:{},verified:false,featured:false,updatedAt:'2026-05-21'},
 {id:6,slug:'dimas-aryasatya',fullName:'Dimas Aryasatya',academicTitle:'S.E.',militaryRank:'Kapten Kal',letting:'CAKRABUANA',batch:'PaPK 27',year:'2020',corps:'Perbekalan',profession:'Logistician',specialization:'Rantai Pasok',region:'DI Yogyakarta',unit:'Kodiklatau',profileImage:'https://i.pravatar.cc/300?img=13',shortBio:'Profesional logistik dengan minat pada rantai pasok berkelanjutan.',education:['S.E. Manajemen'],achievements:['Optimalisasi rantai pasok'],socialLinks:{linkedin:'#'},verified:true,featured:false,updatedAt:'2026-04-18'},
 {id:7,slug:'guntur-wicaksana',fullName:'Guntur Wicaksana',academicTitle:'S.H.',militaryRank:'Lettu Sus',letting:'BIMANTARA',batch:'PaPK 28',year:'2021',corps:'Khusus',profession:'Legal Officer',specialization:'Hukum Publik',region:'Jakarta',unit:'Koopsudnas',profileImage:'https://i.pravatar.cc/300?img=33',shortBio:'Praktisi hukum yang aktif dalam edukasi kepatuhan organisasi.',education:['S.H. Ilmu Hukum'],achievements:['Fasilitator literasi hukum'],socialLinks:{},verified:false,featured:false,updatedAt:'2026-03-12'},
 {id:8,slug:'ayu-sekar-kirana',fullName:'Ayu Sekar Kirana',academicTitle:'M.Psi.',militaryRank:'Lettu Kes',letting:'ALCANTARA',batch:'PaPK 29B',year:'2022B',corps:'Kesehatan',profession:'Psikolog',specialization:'Psikologi Industri',region:'Jawa Timur',unit:'Lanud Iswahjudi',profileImage:'https://i.pravatar.cc/300?img=49',shortBio:'Psikolog yang mendampingi pengembangan SDM dan ketahanan mental.',education:['M.Psi. Psikologi'],achievements:['Program well-being satuan'],socialLinks:{instagram:'#'},verified:true,featured:false,updatedAt:'2026-08-02'},
 {id:9,slug:'fajar-nugroho',fullName:'Fajar Nugroho',academicTitle:'S.Kom.',militaryRank:'Lettu Lek',letting:'DANENDRA',batch:'PaPK 30',year:'2023',corps:'Elektronika',profession:'Data Analyst',specialization:'Keamanan Siber',region:'Jawa Barat',unit:'Satuan Siber',profileImage:'https://i.pravatar.cc/300?img=5',shortBio:'Analis data yang mendalami keamanan informasi.',education:['S.Kom. Ilmu Komputer'],achievements:['Finalis inovasi digital'],socialLinks:{linkedin:'#'},verified:true,featured:false,updatedAt:'2026-08-30'},
 {id:10,slug:'intan-permata-sari',fullName:'Intan Permata Sari',academicTitle:'S.I.Kom.',militaryRank:'Lettu Sus',letting:'DANENDRA',batch:'PaPK 30',year:'2023',corps:'Khusus',profession:'Public Relations',specialization:'Komunikasi Strategis',region:'Bali',unit:'Lanud I Gusti Ngurah Rai',profileImage:'https://i.pravatar.cc/300?img=44',shortBio:'Komunikator strategis dengan fokus pada hubungan komunitas.',education:['S.I.Kom.'],achievements:['Kampanye komunikasi publik'],socialLinks:{instagram:'#'},verified:false,featured:false,updatedAt:'2026-07-25'},
];
export const alumni:Alumni[]=seeds.map(a=>({...a,name:`${a.militaryRank} ${a.fullName}`,rank:a.militaryRank,role:a.profession,city:a.region,initials:a.fullName.split(' ').map(x=>x[0]).slice(0,2).join(''),specialty:a.specialization}));
export const milestones=[['2022','Pendidikan PaPK dimulai'],['29A','Letting Alcantara terbentuk'],['2023','Pengabdian di satuan'],['2026','Jejaring digital diluncurkan']];
export const news=[
 {date:'18 Agustus 2026',tag:'Pengabdian',title:'Alcantara Berbagi: Bakti kesehatan untuk masyarakat pesisir',text:'Kolaborasi lintas korps menghadirkan pemeriksaan kesehatan dan edukasi bagi keluarga nelayan.'},
 {date:'02 Juli 2026',tag:'Prestasi',title:'Alumni 29A raih apresiasi inovasi sistem pemeliharaan',text:'Inovasi pencatatan teknis memperkuat kesiapan operasi dan akurasi pelaporan satuan.'},
 {date:'21 Juni 2026',tag:'Komunitas',title:'Temu virtual lintas penugasan Alcantara',text:'Menjaga silaturahmi dari berbagai wilayah pengabdian melalui agenda berbagi pengalaman.'}
];
