import {useMemo,useState} from 'react';
import {Link,useParams} from 'react-router-dom';
import {motion} from 'framer-motion';
import {ArrowRight,Award,Briefcase,MapPin,Plane,Search,Shield,Users} from 'lucide-react';
import {Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {alumni} from './data';

const reveal={initial:{opacity:0,y:25},whileInView:{opacity:1,y:0},viewport:{once:true,margin:'-70px'},transition:{duration:.6}};
const colors=['#d2ad61','#2789bd','#64b5d8','#8a9db0','#214663'];
const corps=[{name:'Elektronika',value:28},{name:'Penerbang',value:24},{name:'Kesehatan',value:20},{name:'Administrasi',value:16},{name:'Khusus',value:12}];
const professions=[{name:'Aviasi',value:24},{name:'Teknologi',value:22},{name:'Medis',value:20},{name:'Manajemen',value:18},{name:'Lainnya',value:16}];
const regions=[{name:'Jakarta',value:32},{name:'Jawa Barat',value:24},{name:'Jawa Timur',value:19},{name:'Yogyakarta',value:14},{name:'Lainnya',value:11}];
const journey=[['APR 2022','Langkah Pertama','Pendidikan dimulai; beragam latar menyatu dalam satu tujuan.'],['JUL 2022','Nama Alcantara','Identitas 29A lahir: cakrawala luas dan persaudaraan tanpa batas.'],['DES 2022','Pelantikan','Akhir pendidikan sekaligus awal perjalanan pengabdian.'],['2023—KINI','Lintas Cakrawala','Bertugas dan membawa nilai Alcantara ke penjuru nusantara.']];
const photos=[['https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=1400&q=80','Cakrawala pengabdian'],['https://images.unsplash.com/photo-1529070538774-1843cb3265df?auto=format&fit=crop&w=900&q=80','Langkah bersama'],['https://images.unsplash.com/photo-1517976547714-720226b864c1?auto=format&fit=crop&w=900&q=80','Malam tradisi'],['https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=80','Di seluruh negeri']];
function Heading({over,title,copy}:{over:string,title:string;copy?:string}){return <motion.div {...reveal} className="ld-heading"><p>{over}</p><h2>{title}</h2>{copy&&<span>{copy}</span>}</motion.div>}
function Donut({data}:{data:{name:string;value:number}[]}){return <div className="ld-chart"><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" innerRadius="54%" outerRadius="80%" paddingAngle={3}>{data.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/><Legend iconType="circle" iconSize={7}/></PieChart></ResponsiveContainer></div>}
export default function LettingDetail(){const {slug}=useParams();const [q,setQ]=useState('');const members=alumni.filter(a=>a.letting==='ALCANTARA'||a.batch==='PaPK 29A');const found=useMemo(()=>members.filter(a=>`${a.fullName} ${a.profession} ${a.corps} ${a.region}`.toLowerCase().includes(q.toLowerCase())),[q,members]);if(slug!=='alcantara-29a')return <main className="ld-notfound"><h1>Letting belum ditemukan</h1><Link to="/letting">Kembali</Link></main>;return <main className="letting-detail">
 <section className="ld-hero" id="overview"><div className="ld-hero-grid"/><div className="ld-horizon"/><motion.div initial={{opacity:0,y:15}} animate={{opacity:1,y:0}} transition={{duration:1}} className="shell ld-hero-inner"><p>PaPK 29A <i/> 2022A</p><h1>ALCAN<span>TARA</span></h1><div className="ld-motto"><i/>BEYOND THE HORIZON<i/></div><small>Satu nama. Satu perjalanan. Satu cakrawala pengabdian.</small><a href="#identity">Jelajahi perjalanan ↓</a></motion.div><Plane className="ld-plane"/></section>
 <nav className="ld-tabs"><div className="shell">{[['Overview','overview'],['Members','members'],['Timeline','timeline'],['Gallery','gallery'],['Statistics','statistics']].map(x=><a href={`#${x[1]}`} key={x[1]}>{x[0]}</a>)}</div></nav>
 <section className="ld-identity shell" id="identity"><motion.div {...reveal} className="ld-emblem"><label>IDENTITY / EMBLEM</label><div><Plane/><b>29A</b><small>ALCANTARA</small></div><p>Official emblem placeholder</p></motion.div><motion.div {...reveal} className="ld-manifesto"><p>THE NAME WE CARRY</p><h2>Melampaui batas.<br/><em>Menjaga arah.</em></h2><span><strong>Alcantara</strong> adalah pertemuan antara keteguhan dan keluasan pandang. Sebuah nama yang mengingatkan bahwa perjalanan besar bermula dari keberanian untuk menatap lebih jauh.</span><blockquote>“Di mana pun kami mengabdi, langit yang sama selalu menyatukan.”</blockquote></motion.div></section>
 <section className="ld-stats" id="statistics"><div className="shell"><Heading over="ALCANTARA IN NUMBERS" title="Satu letting, beragam pengabdian."/><div className="ld-stat-grid">{[['42','Anggota'],['7','Korps'],['16','Wilayah tugas'],['4','Tahun bersama']].map(x=><motion.div {...reveal} key={x[1]}><b>{x[0]}</b><span>{x[1]}</span></motion.div>)}</div><div className="ld-chart-grid"><article><h3>Corps distribution</h3><p>Komposisi lintas korps</p><Donut data={corps}/></article><article><h3>Profession distribution</h3><p>Keahlian profesional anggota</p><Donut data={professions}/></article><article><h3>Regional distribution</h3><p>Persebaran wilayah pengabdian</p><div className="ld-chart"><ResponsiveContainer><BarChart data={regions} layout="vertical"><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={75} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="value" fill="#2789bd" radius={[0,7,7,0]}/></BarChart></ResponsiveContainer></div></article></div></div></section>
 <section className="ld-members shell" id="members"><div className="ld-member-top"><Heading over="THE PEOPLE" title="Wajah di balik Alcantara." copy="Beragam disiplin. Satu nilai yang sama."/><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari dalam letting…"/></label></div><div className="ld-member-grid">{found.map(a=><motion.article {...reveal} key={a.id}><img src={a.profileImage} alt={a.fullName}/><div><small>{a.militaryRank} · {a.corps}</small><h3>{a.fullName}</h3><p><Briefcase/> {a.profession}</p><p><MapPin/> {a.region}</p><Link to={`/alumni/${a.slug}`}>Lihat profil <ArrowRight/></Link></div></motion.article>)}</div>{!found.length&&<p className="ld-empty">Tidak ada anggota ditemukan.</p>}</section>
 <section className="ld-timeline-section" id="timeline"><div className="shell"><Heading over="OUR JOURNEY" title="Jejak yang membentuk kami."/><div className="ld-timeline">{journey.map((x,i)=><motion.article {...reveal} key={x[1]}><i>0{i+1}</i><span/><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p></motion.article>)}</div><div className="ld-milestones">{[[Award,'18','Penghargaan'],[Users,'12','Kolaborasi'],[Shield,'8','Program pengabdian'],[Briefcase,'6','Forum keahlian']].map(([Icon,n,t])=><div key={String(t)}>{typeof Icon!=='string'&&<Icon/>}<b>{String(n)}</b><span>{String(t)}</span></div>)}</div></div></section>
 <section className="ld-gallery shell" id="gallery"><Heading over="THE ARCHIVE" title="Momen yang tinggal selamanya."/><div className="ld-gallery-grid">{photos.map((x,i)=><motion.figure {...reveal} key={x[0]}><img src={x[0]} alt={x[1]}/><figcaption>0{i+1} · {x[1]}</figcaption></motion.figure>)}</div></section>
 <section className="ld-featured"><div className="shell"><Heading over="FEATURED MEMBERS" title="Cerita dari garis depan."/><div className="ld-feature-grid">{members.slice(0,3).map(a=><article key={a.id}><img src={a.profileImage} alt=""/><div><small>{a.specialization}</small><h3>{a.fullName}</h3><p>{a.shortBio}</p><Link to={`/alumni/${a.slug}`}>Baca perjalanan <ArrowRight/></Link></div></article>)}</div></div></section>
 <section className="ld-stories shell"><Heading over="ALUMNI STORIES" title="Suara yang menjaga ikatan."/><div><article><span>01 / PENGABDIAN</span><h3>Menemukan arti pulang di setiap penugasan</h3><p>Persaudaraan bukan soal berada di tempat yang sama, melainkan selalu hadir ketika dibutuhkan.</p></article><article><span>02 / INOVASI</span><h3>Teknologi sebagai bentuk pengabdian</h3><p>Gagasan kecil tumbuh menjadi sistem yang membantu banyak orang melalui kolaborasi.</p></article></div></section>
 <footer className="ld-footer"><div className="shell"><div><Plane/><b>ALCANTARA <small>PaPK 29A · 2022A</small></b></div><p>Beyond the horizon.<br/>Together in service.</p><a href="#overview">Kembali ke atas ↑</a></div></footer>
 </main>}
